language: android

sudo: false

android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-support
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-15

script:
  - "./gradlew :app:assembleRelease"
    
before_install:
  - chmod +x gradlew
