language: android
android:
  components:
    - build-tools-24.0.0
    - android-22
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-15
    script:
    - ./gradlew :app:assembleRelease
before_install:
 - chmod +x gradlew
